<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="imobiliaria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="imovel" type="ImovelType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ImovelType">
        <xs:sequence>
            <xs:element name="descricao" type="xs:string"/>
            <xs:element name="proprietario" type="ProprietarioType"/>
            <xs:element name="endereco" type="EnderecoType"/>
            <xs:element name="caracteristicas" type="CaracteristicasType"/>
            <xs:element name="valor" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ProprietarioType">
        <xs:sequence>
            <xs:element name="nome" type="xs:string"/>
            <xs:element name="email" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="telefone" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EnderecoType">
        <xs:sequence>
            <xs:element name="rua" type="xs:string"/>
            <xs:element name="bairro" type="xs:string"/>
            <xs:element name="cidade" type="xs:string"/>
            <xs:element name="numero" type="xs:integer" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CaracteristicasType">
        <xs:sequence>
            <xs:element name="tamanho" type="xs:decimal"/>
            <xs:element name="numQuartos" type="xs:integer"/>
            <xs:element name="numBanheiros" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
